apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend
spec:
  parentRefs:
    - name: frontend
      kind: Service
      group: ""
      port: 8080
  rules:
    - backendRefs:
        - name: frontend
          port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: location
spec:
  parentRefs:
    - name: location
      kind: Service
      group: ""
      port: 8081
  rules:
    - backendRefs:
        - name: location
          port: 8081
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: route
spec:
  parentRefs:
    - name: route
      kind: Service
      group: ""
      port: 8083
  rules:
    - backendRefs:
        - name: route
          port: 8083


