apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: frontend-linkerd-annotation.yaml
  - path: location-linkerd-annotation.yaml
  - path: driver-linkerd-annotation.yaml
  - path: route-linkerd-annotation.yaml
