apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: frontend-devmesh-annotation.yaml
  - path: location-devmesh-annotation.yaml
  - path: driver-devmesh-annotation.yaml
  - path: route-devmesh-annotation.yaml


